specVersion: 0.2.0
name: staking-rewards
version: 1.0.0
description: doubletop
repository: https://github.com/subquery/subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 6000000
    mapping:
      file: ./dist/index.js
      handlers:
       - handler: handleSumRewarded
         kind: substrate/EventHandler
         filter:
           module: staking
           method: Rewarded
       - handler: handleStakingRewarded
         kind: substrate/EventHandler
         filter:
            module: staking
            method: Rewarded
